services:
  proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/certbot/letsencrypt:/etc/letsencrypt:ro
      - ./data/certbot/www:/var/www/certbot:ro
    restart: always
  # db:
  #   image: postgres:16-alpine
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   expose:
  #     - "5432"
  #   restart: always
  client:
    build:
      context: ./client/
    expose:
      - 3000
    # depends_on:
    #   - db
    restart: always
  server:
    build:
      context: ./server/
    expose:
      - 3000
    env_file:
      - ./data/.env
    volumes:
      - ./data/shibboleth:/data/shibboleth:ro
    # depends_on:
    #   - db
    restart: always
  # certbot:
  #   image: certbot/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  #   volumes:
  #     - ./data/certbot/letsencrypt:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot